### ISSUE TITLE
[Feature Request]: favicon の設定

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2023#60]
### Is your feature request related to a problem? Please describe

favicon が新しいものに差し替えられていない

### Describe the solution you'd like

↓の favicon を利用する
[favicon.svg.zip](https://github.com/FlutterKaigi/2023/files/11916462/favicon.svg.zip)

![favicon](https://github.com/FlutterKaigi/2023/assets/32213113/1a7fb255-ad75-4619-8511-561639ffddec)

さらに、ブラウザの外観モード（ダークモード）に対応する

```css
@media (prefers-color-scheme: dark) {
  .white {
    fill: #FFF;
    stop-color: #FFF;
   }
}
```

### Describe alternatives you've considered

なし
