### ISSUE TITLE
[Feature Request]: 改善用の Issue テンプレートを作成

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2023#78]
### Is your feature request related to a problem? Please describe

改善用の Issue テンプレートがなく、アプリを改善する意見を出しづらい状況

### Describe the solution you'd like

`.github/ISSUE_TEMPLATE` 配下に↓のようなファイルを追加

```yaml
name: Improve
description: Create a report to help us improve
title: "[Improve]: "
labels: [ "improve", "triage" ]

body:
  - type: textarea
    id: describe
    attributes:
      label: Describe
      description: A clear and concise description.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      value: |
        <img src="" width="320" />
        <video src="" width="320" />
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Please provide details about your environment.
      value: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS 8.1]
        - Browser: [e.g. Chrome, Safari]
        - Version: [e.g. 1.0.0+1]
        - Commit SHA: [e.g. 486ba7defaf1bd6b0deb87db2118c328e5baf529]
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
```

合わせて↓のファイルのラベルを `enhancement` から `feature` `triage` に変更したい
https://github.com/FlutterKaigi/2023/blob/479cc7d775b03ef988ecd650205bfe83d292642e/.github/ISSUE_TEMPLATE/feature_request.yaml

### Describe alternatives you've considered

なし
